spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev


comment.avatar: /images/bg.png
server:
  port: 443
  ssl:
    key-store: classpath:key.pfx
    key-store-password: IUKDPMaK
    keyStoreType: PKCS12