spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #定义jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #日志信息
logging:
  level:
    root: info
    com.hkc: debug
  file:
    name: log/log.log